### ISSUE TITLE
Sth. went wrong while installing this pypi~ anyone helps?

### ISSUE THREAD

**Issue by mapleaimer** [ramusus/django-vkontakte-video#5]
pip install django-vkontakte-video.tar.gz
Collecting django-vkontakte-users
  Downloading django-vkontakte-users-0.8.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\maple\AppData\Local\Temp\pip-build-24r3nf7t\django-vkontakt
e-users\setup.py", line 7, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1949: illegal multibyte sequence

**Comment by ramusus** [comment]
Can you try to run 

```
pip install django-vkontakte-video
```

and 

```
pip install django-vkontakte-users
```

independently and post here output?
?

**Comment by mapleaimer** [comment]
sure, sorry i forgot it...

C:\Users\maple>pip install django-vkontakte-video
Collecting django-vkontakte-video
  Using cached django-vkontakte-video-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\maple\AppData\Local\Temp\pip-build-clqpuq6f\django-vkontakt
e-video\setup.py", line 7, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1854: ill
egal multibyte sequence

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\maple\Ap
pData\Local\Temp\pip-build-clqpuq6f\django-vkontakte-video\

C:\Users\maple>pip install django-vkontakte-users
Collecting django-vkontakte-users
  Using cached django-vkontakte-users-0.8.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\maple\AppData\Local\Temp\pip-build-hur5jv_b\django-vkontakt
e-users\setup.py", line 7, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1949: ill
egal multibyte sequence

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\maple\Ap
pData\Local\Temp\pip-build-hur5jv_b\django-vkontakte-users\

all error codes are as above

**# when i run easy_install django-vkontakte-users and easy install django-vkontakte-video**

C:\Users\maple>easy_install django-vkontakte-users
Searching for django-vkontakte-users
Reading https://pypi.python.org/simple/django-vkontakte-users/
Best match: django-vkontakte-users 0.8.7
Downloading https://pypi.python.org/packages/2d/38/c7698cf623c63e2bb14ad945f72ea
00467291b79e9e52f1da117eb008503/django-vkontakte-users-0.8.7.tar.gz#md5=4a3f1ce2
41922c57a06b8f5bb13bd760
Processing django-vkontakte-users-0.8.7.tar.gz
Writing C:\Users\maple\AppData\Local\Temp\easy_install-57hprxcf\django-vkontakte
-users-0.8.7\setup.cfg
Running django-vkontakte-users-0.8.7\setup.py -q bdist_egg --dist-dir C:\Users\m
aple\AppData\Local\Temp\easy_install-57hprxcf\django-vkontakte-users-0.8.7\egg-d
ist-tmp-a8yt0qt_
Traceback (most recent call last):
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 154, in save_modules
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 195, in setup_context
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 243, in run_setup
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 273, in run
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 242, in runner
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 46, in _execfile
  File "C:\Users\maple\AppData\Local\Temp\easy_install-57hprxcf\django-vkontakte
-users-0.8.7\setup.py", line 7, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1949: illegal
 multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Scripts\easy_install-script.py", line 9, in <module>
    load_entry_point('setuptools==22.0.5', 'console_scripts', 'easy_install')()
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 2294, in main
  File "D:\python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\python\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\python\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 410, in run
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 665, in easy_install
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 695, in install_item
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 876, in install_eggs
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 1115, in build_and_install
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 1101, in run_setup
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 246, in run_setup
  File "D:\python\lib\contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 195, in setup_context
  File "D:\python\lib\contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 166, in save_modules
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 141, in resume
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\pkg_resources_v
endor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 154, in save_modules
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 195, in setup_context
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 243, in run_setup
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 273, in run
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 242, in runner
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 46, in _execfile
  File "C:\Users\maple\AppData\Local\Temp\easy_install-57hprxcf\django-vkontakte
-users-0.8.7\setup.py", line 7, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1949: illegal
 multibyte sequence

C:\Users\maple>easy_install django-vkontakte-video
Searching for django-vkontakte-video
Reading https://pypi.python.org/simple/django-vkontakte-video/
Best match: django-vkontakte-video 0.8.0
Downloading https://pypi.python.org/packages/fa/8d/18aa8512fe720f845de085e71ac62
fb6eb1e3e44a03ff36d90ed27a7bcf9/django-vkontakte-video-0.8.0.tar.gz#md5=b8a256ab
aa7476449610517edd682fa0
Processing django-vkontakte-video-0.8.0.tar.gz
Writing C:\Users\maple\AppData\Local\Temp\easy_install-vft32206\django-vkontakte
-video-0.8.0\setup.cfg
Running django-vkontakte-video-0.8.0\setup.py -q bdist_egg --dist-dir C:\Users\m
aple\AppData\Local\Temp\easy_install-vft32206\django-vkontakte-video-0.8.0\egg-d
ist-tmp-nbgs8cir
Traceback (most recent call last):
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 154, in save_modules
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 195, in setup_context
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 243, in run_setup
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 273, in run
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 242, in runner
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 46, in _execfile
  File "C:\Users\maple\AppData\Local\Temp\easy_install-vft32206\django-vkontakte
-video-0.8.0\setup.py", line 7, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1854: illegal
 multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Scripts\easy_install-script.py", line 9, in <module>
    load_entry_point('setuptools==22.0.5', 'console_scripts', 'easy_install')()
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 2294, in main
  File "D:\python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\python\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\python\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 410, in run
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 665, in easy_install
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 695, in install_item
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 876, in install_eggs
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 1115, in build_and_install
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\comma
nd\easy_install.py", line 1101, in run_setup
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 246, in run_setup
  File "D:\python\lib\contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 195, in setup_context
  File "D:\python\lib\contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 166, in save_modules
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 141, in resume
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\pkg_resources_v
endor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 154, in save_modules
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 195, in setup_context
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 243, in run_setup
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 273, in run
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 242, in runner
  File "D:\python\lib\site-packages\setuptools-22.0.5-py3.5.egg\setuptools\sandb
ox.py", line 46, in _execfile
  File "C:\Users\maple\AppData\Local\Temp\easy_install-vft32206\django-vkontakte
-video-0.8.0\setup.py", line 7, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1854: illegal
 multibyte sequence

C:\Users\maple>

thanks~ sorry for disturbing~
